[package]
name = "plasm-primitives"
version = "0.6.0"
authors = [
    "Takumi Yamashita <takumi@stake.co.jp>",
    "Aleksandr Krupenkin <aleksandr@stake.co.jp>"
]
edition = "2018"

[dependencies]
primitives = { package = "substrate-primitives", git = "https://github.com/staketechnologies/substrate.git", branch = "plasm-master", default-features = false }
sr-primitives = { git = "https://github.com/staketechnologies/substrate.git", branch = "plasm-master", default-features = false }

[features]
default = ["std"]
std = [
	"primitives/std",
	"sr-primitives/std",
]
