[workspace]
members = [
    "bin/node/cli",
    "bin/node/executor",
    "bin/node/primitives",
    "bin/node/rpc",
    "bin/node/runtime",
    "contracts/balances",
    "contracts/balances/.ink/abi_gen",
    "contracts/cash",
    "contracts/cash/.ink/abi_gen",
    "contracts/commitment",
    "contracts/deposit",
    "contracts/predicate",
    "contracts/primitives",
    "frame/operator",
    "frame/session-manager",
]

exclude = [
    "contracts/balances/.ink",
    "contracts/cash/.ink",
]

[profile.release]
# Plasm runtime requires unwinding.
panic = "unwind"
