[workspace]
members = [
    "bin/node/cli",
    "bin/node/rpc",
    "bin/node/runtime",
    "bin/node/primitives",
]

exclude = [
    "vendor",
]

[profile.release]
# Plasm runtime requires unwinding.
panic = "unwind"
