[package]
name = "plasm-cli"
version = "0.6.0"
authors = [
    "Takumi Yamashita <takumi@stake.co.jp>",
    "Aleksandr Krupenkin <aleksandr@stake.co.jp>",
]
description = "Plasm node implementation in Rust."
build = "build.rs"
edition = "2018"
default-run = "plasm-node"

[[bin]]
name = "plasm-node"
path = "bin/main.rs"
required-features = ["cli"]

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
# thidr-party dependencies
futures01 = { package = "futures", version = "0.1.29" }
futures = { version = "0.3.1", features = ["compat"] }
hex-literal = "0.2.1"
serde = "1.0"
serde_json = "1.0"
log = "0.4.8"
structopt = "0.3.3"
jsonrpc-core = "14.0.3"

# primitives
primitives = { package = "substrate-primitives", git = "https://github.com/staketechnologies/substrate.git", branch = "plasm-master" }
sr-primitives = { git = "https://github.com/staketechnologies/substrate.git", branch = "plasm-master" }
babe-primitives = { package = "substrate-consensus-babe-primitives", git = "https://github.com/staketechnologies/substrate.git", branch = "plasm-master" }
grandpa-primitives = { package = "substrate-finality-grandpa-primitives", git = "https://github.com/staketechnologies/substrate.git", branch = "plasm-master" }
inherents = { package = "substrate-inherents", git = "https://github.com/staketechnologies/substrate.git", branch = "plasm-master" }

# client dependencies
client = { package = "substrate-client", git = "https://github.com/staketechnologies/substrate.git", branch = "plasm-master" }
client-api = { package = "substrate-client-api", git = "https://github.com/staketechnologies/substrate.git", branch = "plasm-master" }
chain-spec = { package = "substrate-chain-spec", git = "https://github.com/staketechnologies/substrate.git", branch = "plasm-master" }
txpool = { package = "sc-transaction-pool", git = "https://github.com/staketechnologies/substrate.git", branch = "plasm-master" }
txpool-api = { package = "sp-transaction-pool-api", git = "https://github.com/staketechnologies/substrate.git", branch = "plasm-master" }
network = { package = "substrate-network", git = "https://github.com/staketechnologies/substrate.git", branch = "plasm-master" }
babe = { package = "substrate-consensus-babe", git = "https://github.com/staketechnologies/substrate.git", branch = "plasm-master" }
grandpa = { package = "substrate-finality-grandpa", git = "https://github.com/staketechnologies/substrate.git", branch = "plasm-master" }
offchain = { package = "substrate-offchain", git = "https://github.com/staketechnologies/substrate.git", branch = "plasm-master" }
client-db = { package = "substrate-client-db", git = "https://github.com/staketechnologies/substrate.git", branch = "plasm-master", default-features = false }
substrate-rpc = { git = "https://github.com/staketechnologies/substrate.git", branch = "plasm-master" }
basic-authorship = { package = "substrate-basic-authorship", git = "https://github.com/staketechnologies/substrate.git", branch = "plasm-master" }
substrate-service = { git = "https://github.com/staketechnologies/substrate.git", branch = "plasm-master" }
telemetry = { package = "substrate-telemetry", git = "https://github.com/staketechnologies/substrate.git", branch = "plasm-master" }

# plasm-specific dependencies
plasm-primitives = { path = "../primitives" }
plasm-executor = { path = "../executor" }
plasm-runtime = { path = "../runtime" }
plasm-rpc = { path = "../rpc" }
contracts = { package = "pallet-contracts", git = "https://github.com/staketechnologies/substrate.git", branch = "plasm-master", default-features = false }

# CLI-specific dependencies
tokio = { version = "0.1.22", optional = true }
exit-future = { version = "0.1.4", optional = true }
substrate-cli = { package = "substrate-cli", git = "https://github.com/staketechnologies/substrate.git", branch = "plasm-master", optional = true }
ctrlc = { version = "3.1.3", features = ["termination"], optional = true }

[dev-dependencies]
codec = { package = "parity-scale-codec", version = "1.0" }
service-test = { package = "substrate-service-test", git = "https://github.com/staketechnologies/substrate.git", branch = "plasm-master" }

[build-dependencies]
substrate-cli = { package = "substrate-cli", git = "https://github.com/staketechnologies/substrate.git", branch = "plasm-master" }
build-script-utils = { package = "substrate-build-script-utils", git = "https://github.com/staketechnologies/substrate.git", branch = "plasm-master" }
structopt = "0.3.3"
vergen = "3.0.4"

[features]
default = ["cli"]
cli = [
    "substrate-service/rocksdb",
    "substrate-cli",
    "exit-future",
    "ctrlc",
    "tokio",
]
