[package]
name = "plasm-cli"
version = "1.7.0"
authors = ["Stake Technologies <devops@stake.co.jp>"]
description = "Plasm node implementation in Rust."
build = "build.rs"
edition = "2018"
default-run = "plasm-collator"

[[bin]]
name = "plasm-collator"
path = "bin/main.rs"
required-features = ["cli"]

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
# thidr-party dependencies
codec = { package = "parity-scale-codec", version = "1.3" }
serde = { version = "1.0", features = [ "derive" ] }
structopt = { version = "0.3.8", optional = true }
jsonrpc-core = "15.0"
jsonrpc-pubsub = "15.0"
lazy_static = "1.4"
serde_json = "1.0"
futures = "0.3.4"
log = "0.4.8"
hex = "0.4"

# primitives
sp-core = { git = "https://github.com/paritytech/substrate", branch = "master" }
sp-trie= { git = "https://github.com/paritytech/substrate", branch = "master" }
sp-runtime = { git = "https://github.com/paritytech/substrate", branch = "master" }
sp-inherents = { git = "https://github.com/paritytech/substrate", branch = "master" }
sp-consensus = { git = "https://github.com/paritytech/substrate", branch = "master" }
sp-consensus-babe = { git = "https://github.com/paritytech/substrate", branch = "master" }
sp-finality-grandpa = { git = "https://github.com/paritytech/substrate", branch = "master" }
sp-timestamp = { git = "https://github.com/paritytech/substrate", branch = "master" }
sp-transaction-pool = { git = "https://github.com/paritytech/substrate", branch = "master" }

# client dependencies
sc-client-api = { git = "https://github.com/paritytech/substrate", branch = "master" }
sc-chain-spec = { git = "https://github.com/paritytech/substrate", branch = "master" }
sc-consensus = { git = "https://github.com/paritytech/substrate", branch = "master" }
sc-executor = { git = "https://github.com/paritytech/substrate", branch = "master" }
sc-transaction-pool = { git = "https://github.com/paritytech/substrate", branch = "master" }
sc-network = { git = "https://github.com/paritytech/substrate", branch = "master" }
sc-finality-grandpa = { git = "https://github.com/paritytech/substrate", branch = "master" }
sc-offchain = { git = "https://github.com/paritytech/substrate", branch = "master" }
sc-client-db = { git = "https://github.com/paritytech/substrate", branch = "master", default-features = false }
sc-rpc = { git = "https://github.com/paritytech/substrate", branch = "master" }
sc-basic-authorship = { git = "https://github.com/paritytech/substrate", branch = "master" }
sc-service = { git = "https://github.com/paritytech/substrate", branch = "master" }
sc-telemetry = { git = "https://github.com/paritytech/substrate", branch = "master" }
sc-tracing = { git = "https://github.com/paritytech/substrate", branch = "master" }
sc-consensus-babe = { git = "https://github.com/paritytech/substrate", branch = "master" }

# plasm-specific dependencies
plasm-primitives = { path = "../primitives" }
plasm-runtime = { path = "../runtime" }
plasm-rpc = { path = "../rpc" }

# frame dependencies
frame-system = { git = "https://github.com/paritytech/substrate", branch = "master" }
pallet-transaction-payment = { git = "https://github.com/paritytech/substrate", branch = "master" }
pallet-contracts = { git = "https://github.com/paritytech/substrate", branch = "master" }

# CLI-specific dependencies
sc-cli = { git = "https://github.com/paritytech/substrate", branch = "master", optional = true }

# cumulus dependencies
cumulus-network = { git = "https://github.com/paritytech/cumulus", branch = "master" }
cumulus-service = { git = "https://github.com/paritytech/cumulus", branch = "master" }
cumulus-consensus = { git = "https://github.com/paritytech/cumulus", branch = "master" }
cumulus-primitives = { git = "https://github.com/paritytech/cumulus", branch = "master" }
polkadot-primitives = { git = "https://github.com/paritytech/polkadot", branch = "master" }
polkadot-parachain = { git = "https://github.com/paritytech/polkadot", branch = "master" }
polkadot-service = { git = "https://github.com/paritytech/polkadot", branch = "master" }
polkadot-cli = { git = "https://github.com/paritytech/polkadot", branch = "master", optional = true }

[build-dependencies]
sc-cli = { git = "https://github.com/paritytech/substrate", branch = "master", optional = true }
polkadot-cli = { git = "https://github.com/paritytech/polkadot", branch = "master", optional = true }
build-script-utils = { package = "substrate-build-script-utils", git = "https://github.com/paritytech/substrate", branch = "master" }
structopt = { version = "0.3.8", optional = true }
vergen = { version = "3.0.4", optional = true }

[features]
default = ["cli"]
cli = [
    "sc-cli",
    "polkadot-cli",
    "sc-service/db",
    "structopt",
	"vergen",
]
