[package]
name = "plasm-runtime"
version = "1.7.0"
authors = ["Stake Technologies <devops@stake.co.jp>"]
edition = "2018"
build = "build.rs"

[dependencies]
# third-party dependencies
serde = { version = "1.0.106", optional = true }
codec = { package = "parity-scale-codec", version = "1.3.5", default-features = false, features = ["derive"] }

# primitives
plasm-primitives = { path = "../primitives", default-features = false }
sp-api = { git = "https://github.com/paritytech/substrate", branch = "master", default-features = false }
sp-core = { git = "https://github.com/paritytech/substrate", branch = "master", default-features = false }
sp-io = { git = "https://github.com/paritytech/substrate", branch = "master", default-features = false }
sp-runtime = { git = "https://github.com/paritytech/substrate", branch = "master", default-features = false }
sp-runtime-interface = { git = "https://github.com/paritytech/substrate", branch = "master", default-features = false }
sp-offchain = { git = "https://github.com/paritytech/substrate", branch = "master", default-features = false }
sp-session = { git = "https://github.com/paritytech/substrate", branch = "master", default-features = false }
sp-inherents = { git = "https://github.com/paritytech/substrate", branch = "master", default-features = false }
sp-block-builder = { git = "https://github.com/paritytech/substrate", branch = "master", default-features = false }
sp-transaction-pool = { git = "https://github.com/paritytech/substrate", branch = "master", default-features = false }
sp-std = { git = "https://github.com/paritytech/substrate", branch = "master", default-features = false }
sp-version = { git = "https://github.com/paritytech/substrate", branch = "master", default-features = false }

# frame dependencies
pallet-evm = { default-features = false, git = "https://github.com/PlasmNetwork/frontier", branch = "v0.4-hotfixes" }
pallet-evm-precompile-simple = { default-features = false, git = "https://github.com/PlasmNetwork/frontier", branch = "v0.4-hotfixes" }
frontier-rpc-primitives = { package = "fp-rpc", default-features = false, git = "https://github.com/PlasmNetwork/frontier", branch = "v0.4-hotfixes" }
pallet-ethereum = { default-features = false, git = "https://github.com/PlasmNetwork/frontier", branch = "v0.4-hotfixes" }
frame-executive = { git = "https://github.com/paritytech/substrate", branch = "master", default-features = false }
pallet-authorship = { git = "https://github.com/paritytech/substrate", branch = "master", default-features = false }
pallet-balances = { git = "https://github.com/paritytech/substrate", branch = "master", default-features = false }
pallet-contracts = { git = "https://github.com/paritytech/substrate", branch = "master", default-features = false }
pallet-contracts-primitives = { git = "https://github.com/paritytech/substrate", branch = "master", default-features = false }
pallet-contracts-rpc-runtime-api = { git = "https://github.com/paritytech/substrate", branch = "master", default-features = false }
pallet-indices = { git = "https://github.com/paritytech/substrate", branch = "master", default-features = false }
pallet-nicks = { git = "https://github.com/paritytech/substrate", branch = "master", default-features = false }
pallet-randomness-collective-flip = { git = "https://github.com/paritytech/substrate", branch = "master", default-features = false }
pallet-scheduler = { git = "https://github.com/paritytech/substrate", branch = "master", default-features = false }
pallet-sudo = { git = "https://github.com/paritytech/substrate", branch = "master", default-features = false }
frame-support = { git = "https://github.com/paritytech/substrate", branch = "master", default-features = false }
frame-system = { git = "https://github.com/paritytech/substrate", branch = "master", default-features = false }
frame-system-rpc-runtime-api = { git = "https://github.com/paritytech/substrate", branch = "master", default-features = false }
pallet-timestamp = { git = "https://github.com/paritytech/substrate", branch = "master", default-features = false }
pallet-transaction-payment = { git = "https://github.com/paritytech/substrate", branch = "master", default-features = false }
pallet-transaction-payment-rpc-runtime-api = { git = "https://github.com/paritytech/substrate", branch = "master", default-features = false }
pallet-utility = { git = "https://github.com/paritytech/substrate", branch = "master", default-features = false }

# cumulus dependencies
cumulus-runtime = { git = "https://github.com/PlasmNetwork/cumulus", branch = "master", default-features = false }
cumulus-message-broker = { git = "https://github.com/PlasmNetwork/cumulus", branch = "master", default-features = false }
cumulus-parachain-upgrade = { git = "https://github.com/PlasmNetwork/cumulus", branch = "master", default-features = false }
parachain-info = { git = "https://github.com/PlasmNetwork/cumulus", branch = "master", default-features = false }
xcm-handler = { git = "https://github.com/PlasmNetwork/cumulus", branch = "master", default-features = false }

# polkadot dependencies
polkadot-parachain = { git = "https://github.com/paritytech/polkadot", default-features = false , branch = "master" }
xcm-executor = { git = "https://github.com/paritytech/polkadot", default-features = false , branch = "master" }
xcm-builder = { git = "https://github.com/paritytech/polkadot", default-features = false , branch = "master" }
xcm = { git = "https://github.com/paritytech/polkadot", default-features = false , branch = "master" }

[build-dependencies]
wasm-builder-runner = { package = "substrate-wasm-builder-runner", version = "1.0.5" }

[features]
default = ["std"]
std = [
    "serde",
    "codec/std",
    "sp-std/std",
    "sp-api/std",
    "sp-core/std",
    "sp-io/std",
    "sp-runtime/std",
    "sp-runtime-interface/std",
    "sp-version/std",
    "sp-block-builder/std",
    "sp-transaction-pool/std",
    "sp-inherents/std",
    "plasm-primitives/std",
    "frame-support/std",
    "frame-executive/std",
    "frame-system/std",
    "frame-system-rpc-runtime-api/std",
    "frontier-rpc-primitives/std",
    "pallet-balances/std",
    "pallet-contracts/std",
    "pallet-contracts-primitives/std",
    "pallet-contracts-rpc-runtime-api/std",
    "pallet-evm/std",
    "pallet-evm-precompile-simple/std",
    "pallet-indices/std",
    "pallet-nicks/std",
    "sp-offchain/std",
    "sp-session/std",
    "pallet-randomness-collective-flip/std",
    "pallet-scheduler/std",
    "pallet-ethereum/std",
    "pallet-sudo/std",
    "pallet-timestamp/std",
    "pallet-transaction-payment/std",
    "pallet-transaction-payment-rpc-runtime-api/std",
    "pallet-utility/std",
    "xcm/std",
    "xcm-builder/std",
    "xcm-executor/std",
    "xcm-handler/std",
    "parachain-info/std",
    "polkadot-parachain/std",
    "cumulus-runtime/std",
    "cumulus-message-broker/std",
    "cumulus-parachain-upgrade/std",
]
