name: crates
on:
  pull_request:
  push:
    branches:
      - master
jobs:
  native:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
      - uses: hecrj/setup-rust-action@v1
        with:
          rust-version: 'nightly-2020-02-02'
          targets: 'wasm32-unknown-unknown'
      - name: Checkout the source code
        uses: actions/checkout@master
      - name: Check targets are installed correctly
        run: rustup target list --installed
      - name: Install build tools
        run: cargo install --git https://github.com/alexcrichton/wasm-gc --force
      - name: Build doc
        run: cargo doc --all --all-features --no-deps
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./target/doc
